name: Deploy Landscape

on:
  push:
    branches:
      - main  # Trigger pipeline when changes are pushed to the 'main' branch

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Validate Landscape Settings on AWS EC2
    - name: Validate Landscape Settings on EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }} # Private key stored in GitHub Secrets
        EC2_USER: "ec2-user" # Replace with your EC2 username
        EC2_HOST: ${{ secrets.EC2_PUBLIC_IP }} # EC2 Public IP from GitHub Secrets
      run: |
        echo "Validating settings on EC2..."
        ssh -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" $EC2_USER@$EC2_HOST 'bash -s' << 'EOF'
          cd ~/landscape2 || exit 1
          echo "Running landscape2 validate..."
          landscape2 validate settings --settings-file settings.yml
        EOF

    # Step 3: Deploy to AWS EC2
    - name: Deploy to AWS EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }} # Private key stored in GitHub Secrets
        EC2_USER: "ec2-user" # Replace with your EC2 username
        EC2_HOST: ${{ secrets.EC2_PUBLIC_IP }} # EC2 Public IP from GitHub Secrets
      run: |
        echo "Starting deployment to EC2..."
        ssh -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" $EC2_USER@$EC2_HOST 'bash -s' << 'EOF'
          echo "Running deployment on EC2..."
          pushweb
        EOF
