name: Deploy TSEL Cloud Landscape

on:
  pull_request:
    types: [closed] # Trigger when a pull request is closed
    branches:
      - main        # Target branch must be 'main'

jobs:
  validate-and-deploy:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'feat/') 
    runs-on: self-hosted

    steps:
    # Step 1: Checkout Code
    - name: Clone Git Repository
      run: |
        echo "Cloning repository..."
        git clone https://github.com/lutfieff/tsel-cloud-landscape
        cd ~/tsel-cloud-landscape
        pwd
        ls

    # Step 2: Validate TSEL Cloud Landscape Settings
    - name: Validate TSEL Cloud Landscape Settings
      run: |
        echo "Validating settings..."
        pwd
        landscape2 validate settings --settings-file settings.yml

    # Step 3: Build and Deploy TSEL Cloud Landscape
    - name: Build and Deploy TSEL Cloud Landscape
      run: |
        # Step 1: Build tsel-cloud-landscape
        echo "Building tsel-cloud-landscape..."
        tsel-cloud-landscape build \
          --data-file data.yml \
          --settings-file settings.yml \
          --guide-file guide.yml \
          --logos-path logos \
          --output-dir build

        if [ $? -eq 0 ]; then
          echo "Build completed successfully!"
        else
          echo "Build failed. Please check the error and try again."
          exit 1
        fi

        # Step 2: Copy the build output to the web server directory
        TARGET_DIR="/var/www/tsel-cloud-landscape"
        echo "Copying build output to $TARGET_DIR..."
        sudo mkdir -p $TARGET_DIR
        sudo cp -r build/* $TARGET_DIR

        if [ $? -eq 0 ]; then
          echo "Copy completed! The result can now be accessed via the server."
        else
          echo "Copy failed. Please check permissions and the target directory."
          exit 1
        fi

    # Step 4: Cleanup Temporary Files
    - name: Cleanup Directory
      run: |
        echo "Cleaning up cloned directory..."
        rm -rf ~/tsel-cloud-landscape

        if [ $? -eq 0 ]; then
          echo "Cleanup completed successfully!"
        else
          echo "Cleanup failed. Please check the directory permissions."
          exit 1
        fi
