name: Deploy TSEL Cloud Landscape

on:
  pull_request:
    types: [closed] # Trigger when a pull request is closed
    branches:
      - main        # Target branch must be 'main'

jobs:
  clone:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'feat/')
    runs-on: self-hosted
    outputs:
      clone-dir: ${{ steps.clone.outputs.clone-dir }}

    steps:
    # Step 1: Clone Git Repository
    - name: Clone Git Repository
      id: clone
      run: |
        echo "Cloning repository..."
        git clone https://github.com/lutfieff/tsel-cloud-landscape
        pwd
        ls -la ~/tsel-cloud-landscape

  validate:
    needs: clone
    runs-on: self-hosted

    steps:
    # Step 2: Validate TSEL Cloud Landscape Settings
    - name: Validate TSEL Cloud Landscape Settings
      run: |
        echo "Validating settings..."
        cd ~/tsel-cloud-landscape/tsel-cloud-landscape/tsel-cloud-landscape
        pwd
        landscape2 validate settings --settings-file settings.yml

    # Cleanup on failure
    - name: Cleanup Directory on Failure
      if: failure()
      run: |
        echo "Cleaning up after failure..."
        rm -rf ~/tsel-cloud-landscape


  deploy:
    needs: validate
    runs-on: self-hosted

    steps:
    # Step 3: Build and Deploy TSEL Cloud Landscape
    - name: Build and Deploy TSEL Cloud Landscape
      run: |
        echo "Building tsel-cloud-landscape..."
        cd ~/tsel-cloud-landscape/tsel-cloud-landscape/tsel-cloud-landscape
        landscape2 build \
          --data-file data.yml \
          --settings-file settings.yml \
          --guide-file guide.yml \
          --logos-path logos \
          --output-dir build

        if [ $? -eq 0 ]; then
          echo "Build completed successfully!"
        else
          echo "Build failed. Please check the error and try again."
          exit 1
        fi

        TARGET_DIR="/var/www/my-landscape"
        echo "Copying build output to $TARGET_DIR..."
        sudo mkdir -p $TARGET_DIR
        sudo cp -r build/* $TARGET_DIR

        if [ $? -eq 0 ]; then
          echo "Copy completed! The result can now be accessed via the server."
        else
          echo "Copy failed. Please check permissions and the target directory."
          exit 1
        fi

# Cleanup on failure
    - name: Cleanup Directory on Failure
      if: failure()
      run: |
        echo "Cleaning up after failure..."
        rm -rf ~/tsel-cloud-landscape


  cleanup:
    needs: deploy
    runs-on: self-hosted

    steps:
    # Step 4: Cleanup Temporary Files
    - name: Cleanup Directory
      run: |
        echo "Cleaning up cloned directory..."
        rm -rf ~/tsel-cloud-landscape

        if [ $? -eq 0 ]; then
          echo "Cleanup completed successfully!"
        else
          echo "Cleanup failed. Please check the directory permissions."
          exit 1
        fi
